// <auto-generated />
using Blog.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace web_test_project.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20231229155345_UpdateUserRelations")]
    partial class UpdateUserRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("AuthorUser", b =>
                {
                    b.Property<int>("LikedAuthorsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikedByUsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LikedAuthorsId", "LikedByUsersId");

                    b.HasIndex("LikedByUsersId");

                    b.ToTable("AuthorUser");
                });

            modelBuilder.Entity("Blog.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Blog.Models.BlogPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPages");
                });

            modelBuilder.Entity("Blog.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BlogPageUser", b =>
                {
                    b.Property<int>("LikedBlogPagesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LikedByUsersId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LikedBlogPagesId", "LikedByUsersId");

                    b.HasIndex("LikedByUsersId");

                    b.ToTable("BlogPageUser");
                });

            modelBuilder.Entity("AuthorUser", b =>
                {
                    b.HasOne("Blog.Models.Author", null)
                        .WithMany()
                        .HasForeignKey("LikedAuthorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LikedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BlogPageUser", b =>
                {
                    b.HasOne("Blog.Models.BlogPage", null)
                        .WithMany()
                        .HasForeignKey("LikedBlogPagesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blog.Models.User", null)
                        .WithMany()
                        .HasForeignKey("LikedByUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
